/*----- PROTECTED REGION ID(TMCM_IOStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        TMCM_IOStateMachine.cpp
//
// description : State machine file for the TMCM_IO class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <TMCM_IO.h>

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::TMCM_IOStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  
//  OFF     |  
//  FAULT   |  


namespace TMCM_IO_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : TMCM_IO::is_Value_allowed()
 *	Description : Execution allowed for Value attribute
 */
//--------------------------------------------------------
bool TMCM_IO::is_Value_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Value attribute in Write access.
	/*----- PROTECTED REGION ID(TMCM_IO::ValueStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TMCM_IO::ValueStateAllowed_WRITE

	//	Not any excluded states for Value attribute in read access.
	/*----- PROTECTED REGION ID(TMCM_IO::ValueStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	TMCM_IO::ValueStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================


/*----- PROTECTED REGION ID(TMCM_IO::TMCM_IOStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::TMCM_IOStateAllowed.AdditionalMethods

}	//	End of namespace
