/*----- PROTECTED REGION ID(TMCM_IO.h) ENABLED START -----*/
//=============================================================================
//
// file :        TMCM_IO.h
//
// description : Include file for the TMCM_IO class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TMCM_IO_H
#define TMCM_IO_H

#include <tango.h>
#include <fmt/format.h>
#include "../core/core.h"

/*----- PROTECTED REGION END -----*/	//	TMCM_IO.h

/**
 *  TMCM_IO class description:
 *    
 */

namespace TMCM_IO_ns
{
/*----- PROTECTED REGION ID(TMCM_IO::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::Additional Class Declarations

class TMCM_IO : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TMCM_IO::Data Members) ENABLED START -----*/

	TMCM::ControllerInterface* ci = nullptr;
	bool isOutput;
	int32_t ioID;
	uint8_t bankID;

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::Data Members

//	Device property data members
public:
	//	moduleId:	
	Tango::DevULong	moduleId;
	//	portName:	allowed values:
	//   - OUT[0..7] 
	//   - AIN[0, 4] or 
	//   - In[1, 2, 3, 5, 6, 7]
	string	portName;

//	Attribute data members
public:
	Tango::DevULong	*attr_Value_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TMCM_IO(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	TMCM_IO(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	TMCM_IO(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~TMCM_IO() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();


//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : TMCM_IO::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : TMCM_IO::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute Value related methods
 *	Description: 
 *
 *	Data type:	Tango::DevULong
 *	Attr type:	Scalar
 */
	virtual void read_Value(Tango::Attribute &attr);
	virtual void write_Value(Tango::WAttribute &attr);
	virtual bool is_Value_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : TMCM_IO::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:


	//--------------------------------------------------------
	/**
	 *	Method      : TMCM_IO::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(TMCM_IO::Additional Method prototypes) ENABLED START -----*/

		int8_t ReadInput(TMCM::Module module, TMCM::IO io, TMCM::Bank bank);
		void WriteOutput(bool value);

		void ChangeState(Tango::DevState newState, const std::string& str = "");

		template<typename T>
		bool ValidateResponse(TMCM::TMCMResoponse response, T msg)
		{
			if(response.GetStatus() != TMCM::ReturnCodes::SUCCESS) {
				ChangeState(Tango::ALARM, msg());
				return false;
			}
			return true;
		}

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TMCM_IO::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	TMCM_IO::Additional Classes Definitions

}	//	End of namespace

#endif   //	TMCM_IO_H
